version: '3'
networks:
  spark-network:
services:
  master:
    image: emicdnhub-registry-vpc.cn-hangzhou.cr.aliyuncs.com/001/spark:latest
    container_name: master
    networks:
      - spark-network
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_LOCAL_IP=0.0.0.0   # 监听所有 IP，允许外部访问
    ports:
      - "8080:8080"    # Web UI
      - "7077:7077"    # Spark Master 计算端口
    command: ["/opt/bitnami/spark/sbin/start-master.sh"]
  nginx:
    image: nginx
    restart: always
    networks:
      - spark-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # 挂载 Nginx 配置文件
      - ./logs:/var/log/nginx
    depends_on:
      - master
