version: '3'
networks:
  spark-network:
    driver: host


services:
  master:
    image: emicdnhub-registry-vpc.cn-hangzhou.cr.aliyuncs.com/001/spark:latest
    container_name: master
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_PORT=7078
      - SPARK_MASTER_URL=spark://172.25.158.219:7077
      - SPARK_WORKER_HOST=master
      - SPARK_WORKER_WEBUI_PORT=8080
      - SPARK_LOCAL_IP=master   # 监听所有 IP，允许外部访问
    ports:
      - "8080:8080"    # Web UI
      - "7078:7078"
    command: ["/opt/bitnami/spark/sbin/start-worker.sh","spark://172.25.158.219:7077"]
  nginx:
    image: nginx
    restart: always
    networks:
      - spark-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # 挂载 Nginx 配置文件
      - ./logs:/var/log/nginx
    depends_on:
      - master